version: "3.9"
services:
  mongo-gabysystem:
    image: gabyreload1983/mongo-gabysystem:v1.0.1
    container_name: mongo-gabysystem
    restart: always
    ports:
      - "xxxxx:xxxxx"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ~/mongo-data:/data/db

  api-gabysystem:
    image: gabyreload1983/api-gabysystem:vx.x.x
    container_name: api-gabysystem
    ports:
      - "xxxx:xxxx"
    restart: always
    volumes:
      - ~/pdfHistory:/app/src/public/pdfHistory
      - ~/pdfInvoices:/app/src/public/pdfInvoices
    environment:
      - NODE_ENV=
      - PORT=
      - MONGO_URL=
      - SQL_HOST=
      - ADMIN_FIRST_NAME=
      - ADMIN_LAST_NAME=
      - ADMIN_EMAIL=
      - ADMIN_PASSWORD=
      - ADMIN_CODE_TECHNICAL=
      - ADMIN_ROLE=
      - SQL_USER=
      - SQL_PASSWORD=
      - SQL_DATABASE=
      - SQL_TICKETS_HOST=
      - SQL_TICKETS_USER=
      - SQL_TICKETS_PASSWORD=
      - SQL_TICKETS_DATABASE=
      - PRIVATE_KEY_JWT=
      - MAIL_HOST=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - MAIL_FROM=
      - MAIL_BCC=
      - MAIL_USER_COMPROBANTES=
      - MAIL_PASSWORD_COMPROBANTES=
      - MAIL_FROM_COMPROBANTES=
      - COOKIE_TOKEN=
      - API_VERSION=
      - SALE_NOTE_POSITION=
      - ENABLE_SENDING_INVOICES=
