version: "3.9"
services:
  gabysystem-api:
    image: gabyreload1983/gabysystem-api:vx.x.x
    container_name: gabysystem-api-vx.x.x
    ports:
      - "3400:3000"
    restart: always
    environment:
      - NODE_ENV=
      - PORT=
      - MONGO_URL=
      - SQL_HOST=
      - SQL_USER=
      - SQL_PASSWORD=
      - SQL_DATABASE=
      - PRIVATE_KEY_JWT=
      - MAIL_HOST=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - MAIL_FROM=
      - MAIL_BCC=
      - COOKIE_TOKEN=
      - API_VERSION=
